server:
  port: 8080
spring:
  application:
    name: rent-a-car
  datasource:
    url: jdbc:mysql://localhost:3306/rent_a_car?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
#    password: <your password>
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true