server:
  port: 8080
spring:
  application:
    name: rent-a-car
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    ddl-auto: create
  h2:
    console.enabled: true